sudo: required
language: node_js
cache:
  directories:
  - node_modules
node_js:
- '4.4.5'

install:
  - npm install -g npm
  - npm install

before_script:
- npm install -g angular-cli@1.0.0-beta.8

script: ng build --prod

after_script:
- scripts/push-to-ghpages
