sudo: required
language: node_js
cache:
  directories:
  - node_modules
node_js:
- '4.4.5'

before_script:
- npm install -g angular-cli

script: ng build --prod

after_script:
- script/push-to-ghpages
