sudo: required
language: node_js
cache:
  directories:
  - node_modules
node_js:
- '4.4.5'

before_script:
- npm install -g angular-cli

script: ng github-pages:deploy --gh-token ${GH_TOKEN} --gh-username ${GH_USERNAME}
